name: conditional-bernoulli
channels:
  - defaults
  - pytorch
  - sdrobert
dependencies:
  - python=3.7
  - pytorch=1.10.1
  - ipython
  - pytest
  - seaborn
  - tqdm
  - jupyter
  - pip
  - ruamel_yaml
  - requests
  - setuptools_scm
  - wheel
  - pydrobert-param
  - pydrobert-speech
  - pip:
    - jiwer
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@da70ae9ff06418c5070b882ca25b28c8fe183dc8"
