name: conditional-bernoulli
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.10.1
  - ipython
  - pytest
  - seaborn
  - tqdm
  - jupyter
  - pip
  - ruamel_yaml
  - requests
  - pip:
    - pydrobert-param
    - jiwer
    - "git+https://github.com/sdrobert/pydrobert-speech.git@fd0c48d9db0e4ff189f37d6f655dcac6070c70dd"
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@6b366f912222990f477617cc5cfb76abb0ea4a7a"
