name: conditional-bernoulli
channels:
  - defaults
  - sdrobert
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.10.1
  - ipython
  - pytest
  - pydrobert-param
  - pydrobert-speech
  - seaborn
  - tqdm
  - jupyter
  - pip
  - pip:
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@fb2496483af7cb6279b7b302493a00318290b7c0"
