name: conditional-bernoulli
channels:
  - defaults
  - sdrobert
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.10.1
  - ipython
  - pytest
  - pydrobert-param
  - seaborn
  - tqdm
  - jupyter
  - pip
  - ruamel_yaml
  - pip:
    - "git+https://github.com/sdrobert/pydrobert-speech.git@fd0c48d9db0e4ff189f37d6f655dcac6070c70dd"
    - "git+https://github.com/sdrobert/pydrobert-pytorch.git@cb3eb2ef4becb03143d138c2ba3442945fc70442"
