name: conditional-bernoulli
channels:
  - defaults
  - sdrobert
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.9.0
  - ipython
  - pytest
  - cpuonly
  - pydrobert-param
  - seaborn
  - tqdm
  - jupyter
