model:
  conditional:
    embedding_size: 16
    hidden_size: 128
    merge_method: mix
    num_layers: 3
lm:
  data:
    batch_size: 512
    drop_last: false
  training:
    dropout_prob: 0.3
    swap_prob: 0.3
    early_stopping_patience: 10
    early_stopping_threshold: 0.1