model:
  frontend:
    window_size: 1
    window_stride: 1
    convolutional_layers: 0
    recurrent_type: LSTM
  
  latent:
    merge_cat: true
    hidden_size: 421
  
  conditional:
    hidden_size: 250
am:
  data:
    batch_size: 8
    delta_order: 2
    do_mvn: true
    drop_last: true
  training:
    dropout_prob: 0.0
    swap_prob: 0.0
    aug_er_thresh: 0.5
    weight_noise_std: 0.075
    early_stopping_burnin: 0
    early_stopping_patience: 20
    early_stopping_threshold: 1e-3
    keep_last_and_best_only: true
    optimizer: adam
    momentum: 0.9
  pcb:
    window_size: 1
    window_stride: 1
    recurrent_layers: 3
    convolutional_layers: 0
    recurrent_size: 250
    recurrent_type: LSTM
    recurrent_bidirectional: true
lm:
  data:
    batch_size: 64
    drop_last: true
  training:
    dropout_prob: 0.0
    swap_prob: 0.0
    aug_pp_thresh: 17
    weight_noise_std: 0.075
    early_stopping_patience: 50
    early_stopping_threshold: 0.1
    optimizer: adam
    momentum: 0.9
