model:
  frontend:
    recurrent_layers: 0
    recurrent_size: 250
  latent:
    num_layers: 3
    embedding_size: 123
    hidden_size: 250
  merge:
    cond_input_is_post: false
am:
  data:
    batch_size: 4
  training:
    world_size: 4
  decoding:
    style: beam