model:
  frontend:
    recurrent_layers: 3
    recurrent_size: 421
  latent:
    num_layers: 0
    embedding_size: 0
  merge:
    cond_input_is_post: false
am:
  data:
    batch_size: 16
  decoding:
    style: beam