model:
  frontend:
    window_size: 3
    window_stride: 3
    convolutional_layers: 0
    recurrent_type: LSTM
    recurrent_size: 300
    recurrent_bidirectional: false
  latent:
    hidden_size: 300
  
  conditional:
    hidden_size: 300
am:
  data:
    loader:
      batch_size: 16
      drop_last: false
      num_length_buckets: 5
      size_batch_by_length: true
  training:
    dropout_prob: 0.5
    swap_prob: 0.3
    aug_er_patience: 1
    aug_er_thresh: 1e-3
    mc_samples: 16
    mc_burn_in: 8
    early_stopping_burnin: 20
    early_stopping_patience: 50
    early_stopping_threshold: 1e-3
    keep_last_and_best_only: true
    log10_learning_rate: -4
    # sa_time_size_prop: 0.04
    # sa_freq_size: 4
    # sa_time_num_prop: 0.04
    # sa_freq_num: 1

lm:
  data:
    batch_size: 512
    drop_last: false
  training:
    dropout_prob: 0.3
    swap_prob: 0.3
    early_stopping_patience: 10
    early_stopping_threshold: 0.1