model:
  frontend:
    window_size: 3
    window_stride: 3
    convolutional_layers: 0
    recurrent_type: LSTM

  latent:
    merge_cat: true
    hidden_size: 300
  conditional:
    hidden_size: 300
am:
  training:
    batch_size: 20
    delta_order: 0
    do_mvn: false
    drop_last: true
    dropout_prob: 0.15
    swap_prob: 0.0
    aug_er_thresh: 0.9
    early_stopping_burnin: 0
    early_stopping_patience: 20
    early_stopping_threshold: 1e-3
    keep_last_and_best_only: true
    log10_learning_rate: -4
    optimizer: adam
    momentum: 0.9
    # entropy_init: 1.0
    # entropy_decay: 0.97 ** (1/10000)
    # entropy_floor: 0.1
  pcb:
    window_size: 3
    window_stride: 3
    recurrent_layers: 4
    convolutional_layers: 0
    recurrent_size: 250
    recurrent_type: LSTM
    recurrent_bidirectional: true
lm:
  batch_size: 64
  drop_last: true
  dropout_prob: 0.6
  swap_prob: 0.1
  aug_pp_thresh: 17
  early_stopping_patience: 50
  early_stopping_threshold: 0.1
  optimizer: adam
  momentum: 0.9
