model:
  frontend:
    recurrent_layers: 5
  latent:
    num_layers: 0
    embedding_size: 0
  merge:
    cond_input_is_post: true
am:
  training:
    weight_noise_std: 0.075
  data:
    batch_size: 16
  decoding:
    style: prefix